spring:
  application:
    name: CONFIGURATION-SERVICE
  cloud:
    config:
      server:
        git:
          uri: https://github.com/anishsneh/config-repo         
          searchPaths: '{application}'
          basedir: target/config

server:
  port: 9190
      
eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: true
    